#!/usr/bin/env bash

set -x

if [ $# -ne 2 ];
then
 echo $0 [usb_disk]
 exit 1
fi

usb_disk="$1"
fat32_partition_size=1000

rm -rf /tmp/multipi4
mkdir /tmp/multipi4
cd /tmp/multipi4

mount|grep $usb_disk|awk '{print $1}'|xargs umount

install_prerequisites() {
apt install -y qemu qemu-user-static binfmt-support systemd-container git subversion    
}

prepare_disk() {
usb_disk="$1"

sfdisk -f $usb_disk <<EOF
label: dos
,${fat32_partition_size}MiB,c
,${fat32_partition_size}MiB,c
,,83
EOF

partprobe "${usb_disk}"
sleep 1
mkfs.vfat "${usb_disk}1"
mkfs.vfat -n MULTIPI4 "${usb_disk}2"
mkfs.btrfs -f "${usb_disk}3"  
}

prepare_first_partition() {
usb_disk="$1"
git clone https://github.com/raspberrypisig/multipi4-alpineboot
cd multipi4-alpineboot
./setup.sh
TEMP_BOOT=/tmp/multipi4/alpine
mkdir -p usb2
mount ${usb_disk}2 usb2
cp -rv $TEMP_BOOT/rpi/* usb2
umount usb2
cd ..
}

prepare_second_partition() {
usb_disk="$1"
mkdir usb2
mount ${usb_disk}2 usb2
svn co https://github.com/raspberrypi/firmware/trunk/boot
cp boot/start* boot/fixup* usb2  
umount usb2
}

install_prerequisites
prepare_disk $usb_disk
prepare_first_partition $usb_disk
prepare_second_partition $usb_disk

